version: '2'
services:
  elasticsearch-master:
    build: elasticsearch/
    image: twitterelk/elasticsearch
    environment:
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms5g -Xmx5g"
    networks:
      - docker_elk
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    mem_limit: 10g
    cap_add:
      - IPC_LOCK
    volumes:
      - ./data/master:/usr/share/elasticsearch/data
    container_name: twitterelk_elasticsearch-master
  elasticsearch-node:
    image: twitterelk/elasticsearch
    environment:
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms5g -Xmx5g"
    networks:
      - docker_elk
    depends_on:
      - elasticsearch-master
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    mem_limit: 10g
    cap_add:
      - IPC_LOCK
    volumes:
      - ./data/node:/usr/share/elasticsearch/data
    command: elasticsearch -E discovery.zen.ping.unicast.hosts=elasticsearch-master -E network.host=0.0.0.0 -E discovery.zen.minimum_master_nodes=1
    container_name: twitterelk_elasticsearch-node
  logstash:
    build: logstash/
    command: -f /etc/logstash/conf.d/
    volumes:
      - ./logstash/config:/etc/logstash/conf.d
    networks:
      - docker_elk
    depends_on:
      - elasticsearch-node
    container_name: twitterelk_logstash
  kibana:
    build: kibana/
    networks:
      - docker_elk
    depends_on:
      - elasticsearch-node
    container_name: twitterelk_kibana
    command: kibana -e http://elasticsearch-node:9200 
volumes:
  data:
    driver: local

networks:
  docker_elk:
    driver: bridge
